name: plutus

on:
  push:
    branches: [ main ]

env:
  TAG: "glottologist/plutus-playground"

jobs:

  build_image:
     runs-on: ubuntu-latest

     steps:
       - name: Build maintainer image
         uses: actions/checkout@v2

       - name: Login to DockerHub Registry
         run: echo ${{ secrets.DH_PASS }} | docker login -u ${{ secrets.DH_USER }} --password-stdin

       - name: Get the version
         id: vars
         run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

       - name: Build the tagged Docker image
         run: docker build .  --tag $TAG:${{steps.vars.outputs.tag}}

       - name: Push the tagged Docker image
         run: docker push $TAG:${{steps.vars.outputs.tag}}

       - name: Build the latest Docker image
         run: docker build . --tag $TAG:latest

       - name: Push the latest Docker image
         run: docker push $TAG:latest


