name: plutus

on:
  push:
    branches: [ main ]

env:
  BASETAG: "glottologist/plutus-base"
  PLAYTAG: "glottologist/plutus-playground"

jobs:

  build_image:
     runs-on: ubuntu-latest

     steps:
       - name: Build maintainer image
         uses: actions/checkout@v2

       - name: Login to DockerHub Registry
         run: echo ${{ secrets.DH_PASS }} | docker login -u ${{ secrets.DH_USER }} --password-stdin

       - name: Get the version
         id: vars
         run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

       - name: Build the tagged Docker base image
         run: docker build . -f Dockerfile.base  --tag $BASETAG:${{steps.vars.outputs.tag}}

       - name: Push the tagged Docker base image
         run: docker push $BASETAG:${{steps.vars.outputs.tag}}

       - name: Build the latest Docker base image
         run: docker build . -f Dockerfile.base  --tag $BASETAG:latest

       - name: Push the latest Docker base image
         run: docker push $BASETAG:latest

       - name: Build the tagged Docker playground image
         run: docker build . -f Dockerfile.playgound  --tag $PLAYTAG:${{steps.vars.outputs.tag}}

       - name: Push the tagged Docker playground image
         run: docker push $PLAYTAG:${{steps.vars.outputs.tag}}

       - name: Build the latest Docker playground image
         run: docker build . -f Dockerfile.playground  --tag $PLAYTAG:latest

       - name: Push the latest Docker playground image
         run: docker push $PLAYTAG:latest
