name: plutus

on:
  push:
    branches: [ main ]

env:
  TAG: "glottologist/plutus-playground"

jobs:

  build_image:
     runs-on: ubuntu-latest

     steps:
       - name: Build maintainer image
         uses: actions/checkout@v2

       - name: Login to DockerHub Registry
         run: echo ${{ secrets.DH_PASS }} | docker login -u ${{ secrets.DH_USER }} --password-stdin


       - name: Build the tagged Docker image
         run: VERSION=$(git rev-parse --short HEAD) docker build . --tag $TAG:$VERSION

       - name: Push the tagged Docker image
         run: VERSION=$(git rev-parse --short HEAD) docker push $TAG:$VERSION

       - name: Build the latest Docker base image
         run: docker build .  --tag $TAG:latest

       - name: Push the latest Docker base image
         run: docker push $TAG:latest

